Debug: true
TaurusDBHost: 124.70.86.207
TaurusDBPort: "3306"
TaurusDBUser: u23373490
TaurusDBPassword: "Aa428830"
TaurusDBName: h_db23373490
RedisAddress: localhost:6379
RedisPassword: ""
RedisDatabase: 0
DjangoSecretKey: 2bd+82%dkqf6=xv4*!e8%74$73j_w5s57_5llu8_s9)3yl^$rr
MaxUploadSize : 10485760
LogPath: ./ll.log
